### ISSUE TITLE
Caret characters showing in joined multiline cells

### ISSUE THREAD

**Issue by seatrout** [aidenlx/table-extended#14]
In your demo, you get a list inside a cell by merging vertical cells in the first column and using a line continuation at the end of each second column, like so
```
| column one | Column two 
|--------------|---------------|
|Entry one| - list one|\
|^^| - list two|\
|^^| - list three|
|no more| list here!|
```

But when I try this, the list forms as it should in the right hand column, but the two caret marks display in all the left hand cells. In your demo the cells appear empty in preview and the carets don't display. What am I doing wrong?

**Comment by FekketCantenel** [comment]
It took me way too long tonight to remember that I need to add `-tx-` on a line before the table, so in your example:
```
-tx-
| column one | Column two 
|--------------|---------------|
|Entry one| - list one|\
|^^| - list two|\
|^^| - list three|
|no more| list here!|
```
I figured it out by searching my database for `^^`, looking at other tables which were still working (meaning it's not a new plugin bug), and then spotting the `-tx-` line and smacking myself in the forehead.

**Comment by seatrout** [comment]
But I have got the -tx- line in my code — otherwise the lists wouldn't work at all. See:

```
-tx-
|<div style=width:160px> File</div>|<div style=width:160px> Areas of interest</div>|
|-------------------|---------------------------|
**HW 12/300/3**|German clandestine activity in India. Germany: 117043, 117114, 117444, 117553, 117784-117785, 117860, 117997, 118204-118205, Japan: 117433.|
**HW 12/307/3**|- AD (S)s comments on new orders for Hut 3|\
 ^^ |-  ==Diplomatic Section to move from Elmers School to Berkeley Street Mar 9-10==|\
 ^^ |-  AD (S)'s comments on new orders for Hut 3|\
 ^^ |-  first meeting of W/T I Committee|\
 ^^ |- ==GCCS correspondence with MI-8, AM DDI 4 and MI-6== |\
 ^^ |-  annual leave entitlement for civilians|\
 ^^ |-  disciplining of 5 Wrens at BP, supervision of Wrens billeted at Gayhurst and Crawley Grange^[for background colour] |
```
(And I have tried removing the <div> hack in the header line. The same effect appears)

and this comes out as the screenshot 
![2021-09-12 08_27_20-Floradora - Obsidian v0 12 15](https://user-images.githubusercontent.com/5279653/132977782-ed2a14e4-50f1-4c63-94ea-8eff096df1f5.jpg)
  ..

**Comment by aidenlx** [comment]
Actually, you don't need those `^^` to get the rows on the left to be merged. 
![image](https://user-images.githubusercontent.com/31102694/132983641-8637b818-9a88-458b-a46d-272da7f0455e.png)

**Comment by seatrout** [comment]
This really doesn't work for me, though. If I don't have the caret characters in the first column, only the top cell of the second column appears.

**Comment by aidenlx** [comment]
> If I don't have the caret characters in the first column, only the top cell of the second column appears.

That's odd, do you have an example for this?

**Comment by seatrout** [comment]
Ah! it's **the footnote** that does it.

```
-tx-
|<div style=width:160px> File</div>|<div style=width:160px> Areas of interest</div>|
|-------------------|---------------------------|
**HW 12/300/3**|German clandestine activity in India. Germany: 117043, 117114, 117444, 117553, 117784-117785, 117860, 117997, 118204-118205, Japan: 117433.|
**HW 12/307/3**|- AD (S)s comments on new orders for Hut 3|\
 ^^ |-  ==Diplomatic Section to move from Elmers School to Berkeley Street Mar 9-10==|\
 ^^ |-  AD (S)'s comments on new orders for Hut 3|\
 ^^ |-  first meeting of W/T I Committee|\
 ^^ |- ==GCCS correspondence with MI-8, AM DDI 4 and MI-6== |\
 ^^ |-  annual leave entitlement for civilians|\
 ^^ |-  disciplining of 5 Wrens at BP, supervision of Wrens billeted at Gayhurst and Crawley Grange^[for background colour] |
```

doesn't work
But

```
-tx-
|<div style=width:160px> File</div>|<div style=width:160px> Areas of interest</div>|
|-------------------|---------------------------|
**HW 12/300/3**|German clandestine activity in India. Germany: 117043, 117114, 117444, 117553, 117784-117785, 117860, 117997, 118204-118205, Japan: 117433.|
**HW 12/307/3**|- AD (S)s comments on new orders for Hut 3|\
 ^^ |-  ==Diplomatic Section to move from Elmers School to Berkeley Street Mar 9-10==|\
 ^^ |-  AD (S)'s comments on new orders for Hut 3|\
 ^^ |-  first meeting of W/T I Committee|\
 ^^ |- ==GCCS correspondence with MI-8, AM DDI 4 and MI-6== |\
 ^^ |-  annual leave entitlement for civilians|\
 ^^ |-  disciplining of 5 Wrens at BP, supervision of Wrens billeted at Gayhurst and Crawley Grange|
```

works the way it should. In fact, without the footnote, the original bug (that the caret characters show up) also goes away. 

The obvious workaround is to ~~add a third column to the table for footnotes~~ Just to turn the footnotes into highlighted sections of the relevant notes

**Comment by seatrout** [comment]
So: one issue is that footnotes break the multiple line trick. I'll open a new issue for the next thing I've discovered — two consecutive groups of listed cells to make a group don't work.

**Comment by aidenlx** [comment]
as I still not be able to reproduce this, I'm going to close this for now. 
![image](https://user-images.githubusercontent.com/31102694/133007446-2bab7041-5cd1-47ad-8834-4f2f0d5852ea.png)

```md
-tx-
|<div style=width:160px> File</div>|<div style=width:160px> Areas of interest</div>|
|-------------------|---------------------------|
**HW 12/300/3**|German clandestine activity in India. Germany: 117043, 117114, 117444, 117553, 117784-117785, 117860, 117997, 118204-118205, Japan: 117433.|
**HW 12/307/3**|- AD (S)s comments on new orders for Hut 3|\
  |-  ==Diplomatic Section to move from Elmers School to Berkeley Street Mar 9-10==|\
  |-  AD (S)'s comments on new orders for Hut 3|\
  |-  first meeting of W/T I Committee|\
  |- ==GCCS correspondence with MI-8, AM DDI 4 and MI-6== |\
  |-  annual leave entitlement for civilians|\
  |-  disciplining of 5 Wrens at BP, supervision of Wrens billeted at Gayhurst and Crawley Grange^[for background colour] |
```
