### ISSUE TITLE
Embeds in table not rendered properly since v1.3.2

### ISSUE THREAD

**Issue by ghost** [aidenlx/table-extended#22]
1. Bug: After upgrading to the new version (v1.3.2), all quoted images in the previous table cannot be displayed.
2. Requirement: The ability to merge cells within an unordered list.
![image](https://user-images.githubusercontent.com/69256654/136723198-143234f9-5224-4c13-b404-63feae8aa5aa.png)

**Comment by Asatoshi314** [comment]
我也出現了這個bug，似乎表格把圖片識別成了内部連結，僅顯示圖片的名稱

**Comment by Sunny-27** [comment]
> 奇怪，内部連結雖然無法使用，但是直接使用 ![](url) 可以正常在表格内顯示圖片

到底能显示还是不能显示？我这不能显示图片

**Comment by maiyajj** [comment]
obsidian的块预览也不显示了。![[xxx#xxx]] 会显示成xxx → xxx，而不是正常的块预览
