### ISSUE TITLE
can't use html inside the table

### ISSUE THREAD

**Issue by fgassmann** [aidenlx/table-extended#23]
I used to color things inside tables like this
```
| test  | test |
| --- | ---- |
| <span style="color:green;">text</span>    |   more   |
```
![image](https://user-images.githubusercontent.com/38551877/140066894-a37f51a7-590e-4d68-8c57-03c88600c5e1.png)

but when i add the -tx- to the table all color just disappears

**Comment by ljturmel** [comment]
I have noticed a similar problem with superscripts, e.g., `3.78x10<sup>28</sup>` renders correctly without Table Extended enabled but becomes `3.78x1028` with it enabled.

**Comment by trungng2006** [comment]
This happen even for normal table (not using -tx- on top).
Until the plugin is toggled off, then html tag is rendered again.
