### ISSUE TITLE
`-tx-` tables not rendered in `Export to PDF`

### ISSUE THREAD

**Issue by ftinkere** [aidenlx/table-extended#24]
<img width="348" alt="Screen Shot 2021-11-09 at 3 01 32 PM" src="https://user-images.githubusercontent.com/44341996/140921259-ebc7ee51-4e8a-41f8-881c-183a0e4b4bb3.png">

With -tx- it is text in pdf, but without -tx- is normal table

Obsidian 0.12.19
Table extended 1.4.0
MacOS 10.14.6

**Comment by visrosa** [comment]
From my testing (native pdf export and Pandoc plugin HTML, docx and ODT exports) all of them export the table as text.

**Comment by aidenlx** [comment]
Experimental support in [v1.6.0](https://github.com/aidenlx/table-extended/releases/tag/1.6.0), please add report issues in #30
