### ISSUE TITLE
[Compatibility Request] Markdown-attributes plugin.

### ISSUE THREAD

**Issue by serrga** [aidenlx/table-extended#26]
### Context

There is a plugin [`obsidian-markdown-attributes`](https://github.com/valentine195/obsidian-markdown-attributes) by @valentine195, which seems to be incompatible with `table-extended`.

Interestingly, [`table-extended 1.3.0`](https://github.com/aidenlx/table-extended/releases/tag/1.3.0) is compatible with [`markdown-attributes 1.1.0`](https://github.com/valentine195/obsidian-markdown-attributes/releases/tag/1.1.0).

Any newer version, even [`1.3.1`](https://github.com/aidenlx/table-extended/releases/tag/1.3.1) is incompatible with `markdown-attributes`.

The following table code:

```
| html style                                     | latex           | markdown-attributes                   |
| ---------------------------------------------- | --------------- | ------------------------------------- |
| <div style="background:lightgreen">green</div> | $$\frac{2}{3}$$ | {style="background:lightgreen"} green |
```

in different versions of `table-extended` renders as:

| table-extended                                                          | markdown-attributes                                                                        | example                                                                                                                |
| ----------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------- |
| [`1.3.0`](https://github.com/aidenlx/table-extended/releases/tag/1.3.0) | [`1.1.0`](https://github.com/valentine195/obsidian-markdown-attributes/releases/tag/1.1.0) | ![Screenshot_1](https://user-images.githubusercontent.com/11611643/146694087-0b411d30-5909-446c-8fde-3492444f1220.png) |
| [`1.3.1`](https://github.com/aidenlx/table-extended/releases/tag/1.3.1) | [`1.1.0`](https://github.com/valentine195/obsidian-markdown-attributes/releases/tag/1.1.0) | ![Screenshot_2](https://user-images.githubusercontent.com/11611643/146694088-d7e6948a-f1cd-414d-bf93-47a4cbf5bf37.png) |
| [`1.4.1`](https://github.com/aidenlx/table-extended/releases/tag/1.4.1) | [`1.1.0`](https://github.com/valentine195/obsidian-markdown-attributes/releases/tag/1.1.0) | ![Screenshot_3](https://user-images.githubusercontent.com/11611643/146694089-ce1e53d2-1d19-4d2d-91d1-e3ef347e4191.png) |

### Extra info
As of version `1.3.0`, `table-extended` must be loaded before `markdown-attributes`, else `markdown-attributes` doesn't work inside tables.
community-plugins.json:
```
[
          ⋮
  "table-extended",
  "markdown-attributes",
          ⋮
]
```
Incompatibility occurs regardless of `-tx-` option.

### Possible explanation
Since `1.3.0` is compatible, and `1.3.1` is not, it seems that some new code added in that version broke compatibility. It shouldn't be a problem in `markdown-attributes`, as I understand.

### Expected behavior
Table-extended is expected to cooperate with HTML, latex and markdown-attributes, like so:
![Screenshot_4](https://user-images.githubusercontent.com/11611643/146694780-7bb2153f-4370-4d15-9d0a-14570132ebe6.png)

### Related issues
- #23 − may be connected to this issue.
- #6 − is fixed in newer versions.

**Comment by valentine195** [comment]
> As of version 1.3.0, table-extended must be loaded before markdown-attributes, else markdown-attributes doesn't work inside tables.

I think I know why this is happening. Will investigate a fix (this affects a couple of my plugins).

**Comment by aidenlx** [comment]
seems to be working fine in v0.5.0, feel free to reopen this issue if anything is still broken.

**Comment by serrga** [comment]
It does work for HTML, but unfortunately doesn't seem to work for `markdown-attributes`.

Tested with:
- a fresh vault ([get archive here](https://github.com/aidenlx/table-extended/files/7857272/TestMarkdownAttrs.zip));
- `table-extended 1.5.0`, `markdown-attributes 1.1.0`;
- with `Extended Native Table Syntax` both enabled and disabled;
- both initialising `markdown-attributes` before `table-extended` and vice-versa (`community-plugins.json`);
- on `Obsidian.md 0.12.19`;
- on `Obsidian.md 0.13.19` in both `legacy editor mode` and `live preview mode`.

Markdown-attributes seems to only be compatible with normal tables without `-tx-` tag and `Extended Native Table Syntax` disabled.

What was your testing configuration, maybe I'm missing something?

**Comment by aidenlx** [comment]
locate the problem, seems like I forget to merge it to master branch 😂 it should be solved in v0.15.1 

PS: currently only `style`, `class`, `id` and `data-*` are applied to table cells, let me know if there is any other attrs need to be included

**Comment by serrga** [comment]
Now everything works great, thank you! :)

**Comment by serrga** [comment]
Found a slight bug.
If a cell only contains attributes, but no text, then attributes are not applied to the cell.
- `{style="background-color:green"}` produces a simple empty cell;
- `{style="background-color:green"}123` produces a cell with the text `123` and applied attributes.

It's not that important to fix, but sometimes applying styles to empty cells is useful :)
