### ISSUE TITLE
请教如何去掉2017年下面的两个“^^”?

### ISSUE THREAD

**Issue by zhl111** [aidenlx/table-extended#31]
![image](https://user-images.githubusercontent.com/29135984/149910293-70c266b0-480f-4fd9-a95c-828fa975521f.png)
![image](https://user-images.githubusercontent.com/29135984/149910300-cf803547-757e-421f-881e-9ebd95c064b0.png)

**Comment by aidenlx** [comment]
只要在`-恒大融创碧桂园年内涨幅都在500%以上`这行加^^就行了

**Comment by zhl111** [comment]
我之前就是这样的啦，^^还能加哪？问题还在啊
![image](https://user-images.githubusercontent.com/29135984/150791975-1f57dbb5-4f0d-41e4-a8d2-ccf358a24f57.png)

**Comment by zhl111** [comment]
明白了，是这样的，感谢
![image](https://user-images.githubusercontent.com/29135984/150794270-d9596eb1-4f2a-40a2-af9d-56266e07e28e.png)
