### ISSUE TITLE
Headerless seems not to work

### ISSUE THREAD

**Issue by namtrah** [aidenlx/table-extended#33]
In the following text, headerless tables do not seem to work

|--|--|
| **Text 1** ||
| **Text 2**  ||
| **Text 3** | Text 4 |

using Obsidian 0.13.23

**Comment by aidenlx** [comment]
you need to add a prefix before table to get it working: 
```md
-tx-
|--|--|
| Text 1 ||
| Text 2 ||
| Text 3 | Text 4 |
```
