### ISSUE TITLE
Wikilinks with alias in tables

### ISSUE THREAD

**Issue by StoltHD** [aidenlx/table-extended#7]
Is it possible to add support for wikilinks with alias without the need of escaping the "|" with "\" inside tables, or if that is not a part of your plugin, ask the obsidian team to fix that?

Thanks..

**Comment by StoltHD** [comment]
Just forget about this... there would be other issues.

Sorry

**Comment by aidenlx** [comment]
No need to apologize 😂 It also took me a while to figure out how to insert internal links like `![[link|alias]]` in table. (Just use `\` to escape that like `![[link\|alias]]` in case you haven't figure it out)
