### ISSUE TITLE
RawSection null error when loading

### ISSUE THREAD

**Issue by trungng2006** [aidenlx/table-extended#8]
Im not sure what happen, but everytime obsidian reload, the active pane flickered. And i found this in the error console:
```
main.ts:64 RawSection null, escaping...
TableExtended.processTextSection @ main.ts:64
```

**Comment by aidenlx** [comment]
Flickering is intentional, as existing previews are forced to be rerendered to make sure that tables are handled by plugin. 

As for error log, I think the error is not handled properly so I will probably do something about it later.

**Comment by trungng2006** [comment]
Additional information:
-I think the flicker/error last longer if user have more panes open. When i open 8 panes, the console gave around 250-300 errors and flicker last quite long. if i only open 1 pane, the flicker stop shortly (no error show in the console though)
