### ISSUE TITLE
Feature: Mobile Support

### ISSUE THREAD

**Issue by aidenlx** [aidenlx/table-extended#9]

**Comment by anta-semenov** [comment]
What is a main problem here? I’m software developer and would like to dedicate some time to working on this feature. Would be good to know where I can focus efforts.

**Comment by aidenlx** [comment]
Seems like it's some dependencies that doesn’t work on mobile, the main code doesn’t rely on electron and node to work. My problem is that I don’t have too much time to debug on mobile, to be honest, it’s really painful to debug on iOS devices…

**Comment by liang-0131** [comment]
I really need this feature

**Comment by aidenlx** [comment]
Seems like the blocking issue is resolved somehow in some early updates... I've removed the desktop only flag and pushed a new version, haven't test it fully though but it's working. Leave comment in here if encounter any issues regarding mobile plugin.
